// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Analyte
{
    public int AnalyteId { get; set; }

    public string AnalyteName { get; set; }

    public string DefaultUnit { get; set; }

    public string DefaultReferenceRange { get; set; }

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}