// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Appointment
{
    public int AppointmentId { get; set; }

    public int CustomerId { get; set; }

    public int ConsultantId { get; set; }

    public int ScheduleId { get; set; }

    public string AppointmentStatus { get; set; }

    public string MeetingUrl { get; set; }

    public virtual User Consultant { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual Schedule Schedule { get; set; }
}