// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public int UserId { get; set; }

    public int? RelatedServiceId { get; set; }

    public int? RelatedAppointmentId { get; set; }

    public byte Rating { get; set; }

    public string Comment { get; set; }

    public virtual Appointment RelatedAppointment { get; set; }

    public virtual Service RelatedService { get; set; }

    public virtual User User { get; set; }
}