// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Question
{
    public int QuestionId { get; set; }

    public int CustomerId { get; set; }

    public string Title { get; set; }

    public string QuestionText { get; set; }

    public bool? IsAnonymous { get; set; }

    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    public virtual User Customer { get; set; }
}