// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class TestResult
{
    public int ResultId { get; set; }

    public int BookingId { get; set; }

    public string Notes { get; set; }

    public int IssuedBy { get; set; }

    public DateTime? IssuedAt { get; set; }

    public virtual TestBooking Booking { get; set; }

    public virtual User IssuedByNavigation { get; set; }

    public virtual ICollection<TestResultDetail> TestResultDetails { get; set; } = new List<TestResultDetail>();
}