// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class TestResultDetail
{
    public int DetailId { get; set; }

    public int ResultId { get; set; }

    public string AnalyteName { get; set; }

    public string Value { get; set; }

    public string Unit { get; set; }

    public string ReferenceRange { get; set; }

    public string Flag { get; set; }

    public virtual TestResult Result { get; set; }
}