// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class TestBooking
{
    public int BookingId { get; set; }

    public int CustomerId { get; set; }

    public int ServiceId { get; set; }

    public DateTime? AppointmentTime { get; set; }

    public string BookingStatus { get; set; }

    public bool IsPaid { get; set; }

    public DateTime? BookedAt { get; set; }

    public DateTime? ResultDate { get; set; }

    public virtual User Customer { get; set; }

    public virtual Service Service { get; set; }

    public virtual TestResult TestResult { get; set; }
}